<?php

/**
 * Implements hook_block_info().
 */
function fr_slidets_block_info() {
  $blocks['novelty'] = array(
    'info' => t('Novelty'),
  );
  $blocks['stock'] = array(
    'info' => t('Stock'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function fr_slidets_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'novelty':
      $block['subject'] = t('Novelty from front page');
      $block['content'] = fr_slidets_get_content('field_data_field__new', 'field__new_value', 'Новинки');
      break;

    case 'stock':
      $block['subject'] = t('Stock from front page');
      $block['content'] = fr_slidets_get_content('field_data_field_stock', 'field_stock_value', 'Акції');
      break;
  }
  return $block;
}

function fr_slidets_price_theme ($price) {
  $a = array();
  $a = explode(' ', $price);
  if (strpos($a[0], '.00')) {
    $a[0] = explode('.', $a[0]);
    $a[0] = $a[0][0];
  }

return "$a[0]<span>$a[1]</span>";
}

function fr_slidets_get_content($table, $field, $slider_title = '') {
  $result = db_select($table, 'fn');
        $result->fields('fn', array('entity_id'));
        $result->condition("fn.$field", 1);
        $result = $result->execute();
        $result = $result->fetchAll();

  $output = '<div class="slider-box"><h3>' . $slider_title . '</h3><div class="action acces mySliderWidth"><ul id="' . $table . '" class="clearfix">';

  foreach ($result as $value) {
    $product = commerce_product_load($value->entity_id);

    $result2 = db_select('field_data_field_product_ref', 'fpr');
        $result2->fields('fpr', array('entity_id'));
        $result2->condition('fpr.field_product_ref_product_id', $value->entity_id);
        $result2 = $result2->execute();
        $result2 = $result2->fetchField();
    $node = node_load($result2);

    $linl_to_node = url('node/'. $node->nid, array('absolute' => TRUE));

    $title = $product->title;

    $fp = $product->commerce_price[LANGUAGE_NONE][0];
    $price = commerce_currency_format($fp['amount'], $fp['currency_code']);
    $price = fr_slidets_price_theme($price);

    $fi = $product->field_product_photos[LANGUAGE_NONE][0];
    $variables = array(
      'path'       => $fi['uri'],
      'alt'        => t('Prduct'),
      'title'      => $title,
      'width'      => '169',
      'height'     => '148',
      // 'attributes' => array('class' => 'some-img', 'id' => 'my-img'),
    );
    $img = theme('image', $variables);

    //----------------------------------------------------------------------------------
    // build the line items for shopping cart
    $line_item = commerce_line_item_new($product->type, $order_id = 0);
    $line_item->data['context']['product_ids'] = array($product->product_id);
    $line_item->quantity = 1;
   
    // need to create config for quantity
    $qty = 1;
   
    $form_id = commerce_cart_add_to_cart_form_id(array($product->product_id), $qty);
    $addtocart_form = drupal_get_form($form_id, $line_item);
   
    // we alter the submit form to use our special theme function
    // need to move this to configuration
    $addtocart_form['submit']['#theme'][] = 'vtcommerce_button_small';
   
    $vari = render($addtocart_form);
    //----------------------------------------------------------------------------------

    $output .= "
           <li class=\"product\">
           <div class=\"prw\">
               <a href=\"$linl_to_node\">
                   $img
                 </a>
             </div>
             <div class=\"info-bar\">
               <h4><a href=\"$linl_to_node\">$title</a><span></span></h4>
                 <div class=\"price\">$price</span></div>
                 $vari
             </div>
         </li>";
  }

  $output .='</ul></div><div>
                  <a href="#" class="prew"></a>
                    <a href="#" class="next"></a>
                </div>
            </div>';
  return $output;
}
